- name: 02_ansible-role-XtraDB-Cluster
  hosts: otusdb
  gather_facts: true
  become: true
  roles:
    - role: 02_ansible-role-XtraDB-Cluster
      xtradb_cluster_name: "otus-xtradb-cluster"
      xtradb_sst_user: sstuser
      xtradb_sst_password: s3cr3t
      xtradb_root_password: Root!19Pass

      xtradb_nodes_group: "otusdb"
      xtradb_bind_interface: eth0
#      xtradb_mysql_user: mysql
      xtradb-cluster-nodes: "otusdb"


      xtradb_databases:
        - name: keystone
        - name: otus-test

      xtradb_users:
        - name: keystone
          password: PASSWD
          priv: 'keystone.*:GRANT,ALL'

        - name: otus
          password: Otus!19Pass
          priv: 'otusdb.*:ALL'
          host: '%'
