# tasks for Red Hat Familly
---
- name: Disable SELinux
  selinux:
    state: disabled
#    state: permissive
  when: ansible_selinux.status == 'enabled'

- name: repository installation
  yum_repository:
    file: "{{ xtradb_repo_filename }}" 
    name: "{{ xtradb_repo_name }}"
    description: "{{ xtradb_repo_desc }}"
    baseurl: "{{ xtradb_repo_baseurl }}"
    gpgkey: "{{ xtradb_repo_gpgkey }}"
    gpgcheck: "{{ xtradb_repo_gpgcheck }}"


- name: install percona-release-latest
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: installed

#- name: update percona-release
#  yum:
#    name: percona-release
#    state: latest

...
